name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Pre Build
        run: |
          echo "Before Build my-project"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: ChristineZhaoArmory
          repo: my-project
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: ci.yml
          ref: master
      - name: Post Deploy
        run: |
          echo "Post Deploy my-project"
          sleep 10s
